name: Run Tests and Deploy

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, reopened]
    branches: ["main"]

jobs:
  test:
    name: Run Headless Browser Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Install Dependencies
        run: npm install

      - name: Run Headless Browser Tests
        run: |
          npx mocha test.html --reporter spec --no-timeouts --exit --require jsdom-global/register

  deploy:
    name: Deploy to GitHub Pages
    needs: test
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./  # cambia esto si tu sitio está en otro subdirectorio

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
