name: Roman Converter CI/CD

permissions:
  contents: read
  pages: write
  id-token: write

on:
  push:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run HTMLHint
        run: |
          echo "Installing HTMLHint..."
          sudo npm install -g htmlhint
          htmlhint index.html test.html --config .htmlhintrc

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run html-proofer
        run: |
          echo "Installing Ruby and html-proofer..."
          sudo apt-get update
          sudo apt-get install -y ruby-full build-essential
          sudo gem install html-proofer
          echo "Running html-proofer..."
          htmlproofer . --disable-external

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build project
        run: |
          echo "Running static build step..."
          mkdir -p dist
          cp index.html test.html tests.js dist/
          echo "Build complete. Files copied to ./dist"

      - name: Dummy file to workaround GitHub Actions bug
        run: |
          mkdir -p dist
          touch dist/.dummy

      - name: Workaround: preload upload-artifact
        uses: actions/upload-artifact@v3
        with:
          name: dummy
          path: ./dist/.dummy

      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./dist

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
    steps:
      - name: Setup GitHub Pages
        uses: actions/configure-pages@v2

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
