name: CD Pipeline Roman Converter

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, reopened]
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Instalar HTMLHint
        run: sudo npm install -g htmlhint
      - name: Lint HTML
        run: htmlhint *.html || true

  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Instalar Puppeteer y Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser
          sudo npm install -g puppeteer
      - name: Test con Chromium
        run: chromium-browser --headless --no-sandbox --disable-gpu --dump-dom index.html

  deploy:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - uses: actions/checkout@v3
      - name: Crear carpeta de despliegue
        run: |
          mkdir public
          cp *.html *.js *.css public/
      - name: Subir artefactos
        uses: actions/upload-pages-artifact@v2
        with:
          path: public
      - name: Desplegar en GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v2

        uses: actions/deploy-pages@v2
