name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Test
        run: |
          echo "Running tests..."
          node_modules/.bin/mocha-headless-chrome -f test.html --args no-sandbox

      - name: Build
        run: echo "🔨 Build step (replace this with real build if needed)"

      - name: Deploy
        run: echo "🚀 Deploy step (replace this with real deploy if needed)"
