name: Roman Converter CI/CD

permissions:
  contents: write
  pages: write
  id-token: write

on:
  push:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run HTMLHint
        run: |
          npm install -g htmlhint
          htmlhint index.html test.html || true

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Run tests
        run: |
          node tests-node.js

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: test
    if: success()
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build project
        run: |
          mkdir -p _site
          cp index.html test.html tests.js _site/
          touch _site/.nojekyll

      - name: Upload site artifact
        uses: actions/upload-artifact@v3
        with:
          name: site
          path: _site

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    if: success()
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download built site
        uses: actions/download-artifact@v3
        with:
          name: site
          path: _site

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git checkout --orphan gh-pages
          git reset --hard
          cp -r _site/* .
          touch .nojekyll
          rm -rf _site
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push -f origin gh-pages
