name: cd-pipeline

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Lint HTML files
        uses: chabad360/htmlproofer@v1.0.5
        with:
          directory: .
        continue-on-error: true  # evita que el pipeline falle por errores de lint

      - name: Run tests in browser
        run: |
          echo "Testing using headless browser is not supported natively here."
          echo "You can test manually at test.html"
        continue-on-error: true

      - name: Build (no-op)
        run: echo "No build step required for static HTML project."

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: .

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2

