name: Roman Converter CI/CD

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run HTMLHint
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install -g htmlhint
      - run: htmlhint index.html

  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Launch test server
        run: |
          npm install -g http-server
          http-server -p 8080 &

      - name: Run Tests in headless browser
        uses: cypress-io/github-action@v6
        with:
          start: http-server -p 8080
          wait-on: 'http://localhost:8080/test.html'
          browser: chrome

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
