name: CD Pipeline for Roman Converter (sin npm)

on:
  push:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Instalar HTMLHint
        run: |
          sudo npm install -g htmlhint
      - name: Ejecutar HTMLHint
        run: htmlhint index.html test.html || true

  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Instalar dependencias necesarias
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb
          sudo npm install -g puppeteer
      - name: Ejecutar tests en navegador headless
        run: |
          xvfb-run google-chrome --headless --disable-gpu --no-sandbox --disable-dev-shm-usage --dump-dom index.html

  deploy:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v3
      - name: Preparar archivos para publicación
        run: |
          mkdir public
          cp *.html *.css *.js public/ || true
      - name: Subir artefactos a GitHub Pages
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./public
      - name: Deploy a GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
