name: Roman Converter CI/CD

permissions:
  contents: write
  pages: write
  id-token: write

on:
  push:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run HTMLHint
        run: |
          echo "Installing HTMLHint..."
          sudo npm install -g htmlhint
          htmlhint index.html || true

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Run tests
        run: node tests-node.js

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build project
        run: |
          echo "Running static build step..."
          mkdir -p _site
          cp index.html _site/
          echo "Build complete. Files copied to ./_site"

      - name: Add .nojekyll file
        run: touch _site/.nojekyll

      - name: Create artifact
        run: |
          cd _site
          tar -czvf ../site.tar.gz *
          cd ..

      - name: Store built site
        uses: actions/cache@v3
        with:
          path: site.tar.gz
          key: site-${{ github.run_id }}-${{ github.run_number }}

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Restore built site
        uses: actions/cache@v3
        with:
          path: site.tar.gz
          key: site-${{ github.run_id }}-${{ github.run_number }}

      - name: Extract site
        run: |
          mkdir -p _site
          tar -xzvf site.tar.gz -C _site

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          git checkout --orphan gh-pages
          git reset --hard

          cp -r _site/* .

          touch .nojekyll
          rm -rf _site

          git add .
          git commit -m "Deploy to GitHub Pages"
          git push -f origin gh-pages

          SITE_URL="https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/"
          echo "::notice title=GitHub Pages URL::$SITE_URL"
          echo "======================= INFORMACIÓN IMPORTANTE ======================="
          echo "Tu sitio está publicado en: $SITE_URL"
          echo "Puede tardar unos minutos en estar disponible."
          echo "=================================================================="
