name: Roman Converter CI/CD

on:
  push:
    branches:
      - main

jobs:
  cd-pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Lint
      run: |
        echo "Installing HTMLHint..."
        sudo npm install -g htmlhint
        htmlhint index.html test.html --config .htmlhintrc

    - name: Test
      run: |
        echo "Installing Ruby and html-proofer..."
        sudo apt-get update
        sudo apt-get install -y ruby-full build-essential
        sudo gem install html-proofer
        echo "Running html-proofer..."
        htmlproofer . --disable-external

    - name: Build
      run: |
        echo "Running static build step..."
        mkdir -p dist
        cp index.html test.html tests.js dist/
        echo "Build complete. Files copied to ./dist"

    - name: Deploy
      uses: actions/deploy-pages@v2
      with:
        artifact_name: github-pages
        path: ./dist
